name: CI

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'test/**'
      - 'requirements.txt'
      - '.github/workflows/**'
  pull_request:
    paths: [ '**' ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r test/requirements.txt \
                      ruff black isort pyright mypy pytest-cov -q

      - name: Run ruff
        run: ruff check . --exit-non-zero-on-fix

      - name: Run isort
        run: isort . --check-only

      - name: Run black
        run: black . --check --diff

      - name: Run pyright
        run: pyright

      - name: Run tests
        run: pytest -v test/
